// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDtpvLcB4nz3YqPMtKWdOvzkpDj_sh6mTc',
    appId: '1:399042818507:web:377982e5ac0c729252064e',
    messagingSenderId: '399042818507',
    projectId: 'smartcivicwatchaut',
    authDomain: 'smartcivicwatchaut.firebaseapp.com',
    databaseURL: 'https://smartcivicwatchaut-default-rtdb.firebaseio.com',
    storageBucket: 'smartcivicwatchaut.firebasestorage.app',
    measurementId: 'G-4EEKBPSYXP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDz46zppjfHvba9eN6cxmr6_lvik922DJE',
    appId: '1:399042818507:android:944fe6bd857e794e52064e',
    messagingSenderId: '399042818507',
    projectId: 'smartcivicwatchaut',
    databaseURL: 'https://smartcivicwatchaut-default-rtdb.firebaseio.com',
    storageBucket: 'smartcivicwatchaut.firebasestorage.app',
  );
}
